### ISSUE TITLE
No data jsons after installing with pip

### ISSUE THREAD

**Issue by bodqhrohro** [sebastien/fake#1]
download_url points to https://github.com/sebastien/fake/tarball/0.9.0, but it returns 404, so data are not downloaded.

**Comment by sebastien** [comment]
Thanks, I fixed it, it should work now!

**Comment by bodqhrohro** [comment]
The tarball is in place now, but there is still something wrong with the package so data are not downloaded. If I install the package directly from GitHub, it works well.

**Comment by sebastien** [comment]
Could you be more specific? Which functions are you calling that break?

**Comment by bodqhrohro** [comment]
Any functions that are using a data file: for example, name(), country(), email(). They fail with `No such file or directory` error, as there are no any JSON files in `site-packages/fake/data` directory.

**Comment by sebastien** [comment]
I've tried again with `0.9.1` -- honestly, `setup.py` is an incredible mess for managing extra files. Let me know if it worked!

**Comment by bodqhrohro** [comment]
Yes, it works now. Thank you.

**Comment by sebastien** [comment]
Thanks for reporting!
